- src/brainbrowser/lib/loader.js
and use content_type to determine unzipped content
> use pako to unzip url content

- src/brainbrowser/lib/color-map.js
> #697: add margin

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1624: add drawGridXYZ

- src/brainbrowser/surface-viewer/modules/loading.js
> #1638: dynamic updateColorMap

- src/brainbrowser/surface-viewer/modules/loading.js
> Catch up with master

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1660: add callback

- src/brainbrowser/surface-viewer/modules/loading.js
> #1883: add loadIntensityDataFromText

- src/brainbrowser/volume-viewer/lib/panel.js
> #1953 add volume border and change border style

- src/brainbrowser/lib/color-map.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> #2061: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #2061 add move flag for surf

- src/brainbrowser/lib/color-map.js
> #2077: bugfix

- src/brainbrowser/lib/color-map.js
> #2100 fix colorbar

- src/brainbrowser/lib/color-map.js
> #2611 add box to movable colorbar

- src/brainbrowser/lib/color-map.js
> #2611 colorbar style

- src/brainbrowser/lib/color-map.js
> #2737 consistent colormap

- src/brainbrowser/surface-viewer/modules/annotations.js
> #2740: bugfix

- src/brainbrowser/lib/color-map.js
> #2830 fix percent colormap max text

- src/brainbrowser/core/tree-store.js
- src/brainbrowser/lib/loader.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> #2787 clear annotation fix

- src/brainbrowser/lib/color-map.js
> #2844: bugfix

- src/brainbrowser/volume-viewer/lib/panel.js
> #2943 correct vol view error

- src/brainbrowser/lib/color-map.js
> #2844 colormap label presicion

- src/brainbrowser/lib/events.js
- src/brainbrowser/lib/utils.js
- src/brainbrowser/surface-viewer/lib/three.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/minc.js
> 2957 release1.4 liyachuan clear viz memory

- src/brainbrowser/lib/events.js
- src/brainbrowser/lib/utils.js
- src/brainbrowser/surface-viewer/lib/three.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/minc.js
> Release v1.4 => master

- src/brainbrowser/volume-viewer/modules/loading.js
> #3025 remove unnecessary remove listener for correct change region bug

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/loading.js
> 2957 release1.5 liyachuan clear memory

- src/brainbrowser/surface-viewer/modules/loading.js
> #3987 check data obj is valid

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/loading.js
> Release v1.5 => master

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> 3438 surface add drawline

- src/brainbrowser/surface-viewer/modules/rendering.js
> #3539: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> 3548 feature bold snapshot liangfz bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/modules/loading.js
> #3561: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #3545: bugfix

- src/brainbrowser/volume-viewer/modules/loading.js
> #3581: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #3580: bugfix

- src/brainbrowser/volume-viewer/lib/panel.js
> #3600-折线图点击放大缩小多出一条线bug fix

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> 3662 feature bold snapshot liyachuan cursor to voxel

- src/brainbrowser/volume-viewer/modules/loading.js
> #3677: bugfix

- src/brainbrowser/volume-viewer/lib/panel.js
> #3627: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #3672: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
> 3721 feature bold snapshot liangfz bugfix

- src/brainbrowser/volume-viewer/modules/loading.js
> #3719: bugfix

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> #3720: bugfix

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> #3701: bgufix

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> #3833: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
> #3922: 添加单位

- src/brainbrowser/volume-viewer/modules/loading.js
> #3929: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> 3947 feat bold snapshot liangfz bugfix

- src/brainbrowser/surface-viewer/modules/annotations.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> #2787: annotations reset

- src/brainbrowser/surface-viewer/modules/rendering.js
> #4032: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #4033 correct clear poly line bug

- src/brainbrowser/surface-viewer/modules/rendering.js
> 4046 master liangfz bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #4034: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> Merge master into feature-refactor-upload

- src/brainbrowser/surface-viewer/modules/rendering.js
> #4088: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #4094 correct surface layout bug

- src/brainbrowser/lib/utils.js
> 335 master build mac

- src/brainbrowser/lib/utils.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> Merge master

- src/brainbrowser/lib/color-map.js
> #3971 add logP color element

- src/brainbrowser/surface-viewer/modules/loading.js
> #3972 add load intensity data and format function

- src/brainbrowser/lib/color-map.js
> #3972 correct colorbar bug

- src/brainbrowser/surface-viewer/modules/color.js
> #4204 correct js bug

- src/brainbrowser/lib/color-map.js
> #4216 correct colorbar filter

- src/brainbrowser/lib/color-map.js
> #4252 reverse colorbar

- src/brainbrowser/lib/color-map.js
> 4297 master qjh color bar

- src/brainbrowser/lib/color-map.js
> Merge code from master branch

- src/brainbrowser/lib/color-map.js
> #4297 add Add special condition judgment

- src/brainbrowser/surface-viewer/modules/color.js
- src/brainbrowser/surface-viewer/modules/loading.js
> #4362 correct colormap bug

- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/overlay-aligned.js
> 4359 feature refactor liyachuan add vol opacity

- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/rendering.js
> #4381 correct volume update bug

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> #3291: add surface Opacity

- src/brainbrowser/lib/color-map.js
- src/brainbrowser/surface-viewer/modules/color.js
- src/brainbrowser/surface-viewer/modules/loading.js
> merge into ind

- src/brainbrowser/lib/color-map.js
- src/brainbrowser/surface-viewer/modules/color.js
- src/brainbrowser/surface-viewer/modules/loading.js
> #4436 add filter color by sel parcels

- src/brainbrowser/surface-viewer/modules/rendering.js
> #4533: add grid

- src/brainbrowser/volume-viewer/modules/loading.js
> #4578 add try catch for dom api

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> #4588: add highlightTrajectorys

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/rendering.js
> #4578 show targets on volume

- src/brainbrowser/volume-viewer/volume-loaders/minc.js
- src/brainbrowser/volume-viewer/volume-loaders/overlay-aligned.js
> #4695 merge risk map data

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/rendering.js
> 4733 feature refactor reset layout

- src/brainbrowser/lib/color-map.js
> #4714: colormap 支持 0-1

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/rendering.js
> #4733 set showTarget and showTrajectory

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> #4876 add hideBorder for volume

- src/brainbrowser/surface-viewer/modules/rendering.js
> 4900 feature refactor liyachuan demo update

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
> #4900 correct target line

- src/brainbrowser/volume-viewer/modules/loading.js
> #4960 correct import math

- src/brainbrowser/volume-viewer/modules/loading.js
> #4960 count vessel distance

- src/brainbrowser/volume-viewer/modules/loading.js
> #4960 correct fly volume position

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> 5057 feature refactor liyachuan check risk volume

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> #5057 correct volume init cursor

- src/brainbrowser/volume-viewer/modules/loading.js
> #4972 correct volume multi show bug

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> 5176 feature refactor upload liangfz bugfix

- src/brainbrowser/volume-viewer/modules/loading.js
> #5191 correct volume dispear bug

- src/brainbrowser/surface-viewer/modules/loading.js
> #4997: bugfix

- src/brainbrowser/volume-viewer/modules/loading.js
> #5024 correct math metric bug

- src/brainbrowser/lib/color-map.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/overlay-aligned.js
> 5204 feature refactor liyachuan fly volume bug

- src/brainbrowser/lib/loader.js
> #5033 correct volume loader js bug

- src/brainbrowser/lib/loader.js
- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/mgh.js
- src/brainbrowser/volume-viewer/volume-loaders/minc.js
- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> #5291 add abort surface and volume xhr methods

- src/brainbrowser/lib/loader.js
- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/mgh.js
- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> 5291 feature refactor liyachuan optimize viz

- src/brainbrowser/surface-viewer/modules/loading.js
> #4984 set surface init opacity

- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> #4984 remove error code

- src/brainbrowser/surface-viewer.js
> #5019 try worker error

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> #5390 add console for debug

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> #5390 correct console

- src/brainbrowser/surface-viewer/modules/loading.js
> #5390 remove debug console

- src/brainbrowser/workers/gifti.worker.js
- src/brainbrowser/workers/mniobj.worker.js
> #5003 check input data valid

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/workers/gifti.worker.js
- src/brainbrowser/workers/mniobj.worker.js
> #5418 correct loading bug

- src/brainbrowser/surface-viewer.js
> #5010 correct surface multi update bug

- src/brainbrowser/workers/mniobj.worker.js
> #5010 add mni data.trim check

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/workers/mniobj.worker.js
> #5003 correct surface bug

- src/brainbrowser/workers/mniobj.worker.js
> 5003 feature refactor liyachuan correct surface bug

- src/brainbrowser/workers/mniobj.worker.js
> #5003 correct transfer bug

- src/brainbrowser/volume-viewer/modules/loading.js
> #5650 opt volume memory

- src/brainbrowser/lib/color-map.js
> #5669 correct 17 region colormap bug

- src/brainbrowser/volume-viewer/modules/loading.js
> #5686 correct slice fly bug

- src/brainbrowser/surface-viewer/modules/color.js
> #5731 correct color error

- src/brainbrowser/surface-viewer/modules/color.js
- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/loading.js
> #5731 correct loading js bug

- src/brainbrowser/surface-viewer/modules/rendering.js
> #5945: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
> 5969 master liyachuan correct traj size

- src/brainbrowser/volume-viewer/modules/loading.js
> #6044 add volume data func cb

- src/brainbrowser/volume-viewer/modules/loading.js
> #6044 correct volume color map

- src/brainbrowser/lib/color-map.js
> #6109 correct fc vol colormap

- src/brainbrowser/surface-viewer/modules/loading.js
> #5856 Add format data cb

- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> #6109 correct nifti step

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
> #6138 correct traj length

- src/brainbrowser/volume-viewer/lib/panel.js
> #6141 show solid traj line when target is on the volume

- src/brainbrowser/surface-viewer/modules/color.js
- src/brainbrowser/surface-viewer/modules/loading.js
> #6272 Brain Color Map update

- src/brainbrowser/volume-viewer/volume-loaders/minc.js
> #6281 correct fetch world by rotio

- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> #6300 correct step rotio name

- src/brainbrowser/surface-viewer/modules/color.js
> #6334 bug fix

- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/rendering.js
> 6495 feature safe liyachuan sel parcel from vol

- .gitignore
- src/brainbrowser/volume-viewer/lib/panel.js
> add lineWidth of seeg trajectory

- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/volume-loaders/overlay-aligned.js
> Reduce the number of cycles

- src/brainbrowser/volume-viewer/lib/panel.js
> #6600 correct trajs position

- src/brainbrowser/volume-viewer/lib/panel.js
> #6608 show entry and target

- src/brainbrowser/surface-viewer/modules/loading.js
> 修改surface 材质,避免光照影响

- src/brainbrowser/volume-viewer/volume-loaders/overlay-aligned.js
> #6677: add issafety

- src/brainbrowser/volume-viewer/lib/panel.js
> updatemouse position 其实就是将volume position 方法照搬了一次,避免鼠标滑动时,影响光标.

- src/brainbrowser/volume-viewer/lib/panel.js
> #6753:delete console

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
> 6587 feature safety liyachuan cancel config

- src/brainbrowser/volume-viewer/lib/panel.js
> #6779: bugfix

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
> #6879 correct safety vol traj len and remove console

- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> a6879 feature safety remove console

- src/brainbrowser/volume-viewer/modules/loading.js
> #6985: bugfix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 free gpu memory

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 clear surface cached

- src/brainbrowser/volume-viewer/lib/panel.js
> #7022 correct show trajs bug

- .gitignore
- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
- src/brainbrowser/volume-viewer/volume-loaders/overlay-aligned.js
> Feature safety assistance

- .gitignore
- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
- src/brainbrowser/volume-viewer/volume-loaders/overlay-aligned.js
> Master --> detect

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 release webgl renderer gpu memory data

- src/brainbrowser/surface-viewer/modules/rendering.js
> 1915 master liyachuan release gpu

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 remove unused code

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 correct check isWin and desktop code

- src/brainbrowser/surface-viewer.js
- src/brainbrowser/surface-viewer/modules/rendering.js
> 7058 detect qjh bug fix

- src/brainbrowser/surface-viewer/modules/rendering.js
> #6983 rendering double measure

- src/brainbrowser/surface-viewer/modules/loading.js
> #7087 remove invalid field

- .gitignore
- src/brainbrowser/surface-viewer/modules/loading.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/loading.js
- src/brainbrowser/volume-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/volume-loaders/nifti1.js
- src/brainbrowser/volume-viewer/volume-loaders/overlay-aligned.js
> master to feature

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 reset release gpu for win

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 release memory for win

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 correct release gpu

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 free memory

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1915 remove dumply code

- src/brainbrowser/surface-viewer/modules/rendering.js
> #7134 cache render fn

- src/brainbrowser/surface-viewer/modules/loading.js
> #7296 correct risk bug

- src/brainbrowser/surface-viewer/modules/annotations.js
> #7554 add update dots

- src/brainbrowser/surface-viewer/modules/annotations.js
- src/brainbrowser/surface-viewer/modules/loading.js
> Feature item patch

- src/brainbrowser/surface-viewer/modules/annotations.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/rendering.js
> 2182 feature init point draw point

- src/brainbrowser/surface-viewer/modules/annotations.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- src/brainbrowser/volume-viewer/lib/panel.js
- src/brainbrowser/volume-viewer/modules/rendering.js
> #2182 add update marks for surf and vol

- src/brainbrowser/volume-viewer/lib/panel.js
> #2182 update point radius

- src/brainbrowser/surface-viewer/modules/annotations.js
- src/brainbrowser/volume-viewer/lib/panel.js
> #2182 correct vol voxel by volume headers

- src/brainbrowser/surface-viewer/modules/rendering.js
> #1940 bug fix

- src/brainbrowser/surface-viewer/modules/annotations.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- #1940 bug fix
- #1940 bug fix
> merge master into feature-nodejs-upgrade

- src/brainbrowser/volume-viewer/modules/loading.js
> #2182 #2355 update i j k sort by volume header

- src/brainbrowser/surface-viewer/modules/annotations.js
- src/brainbrowser/surface-viewer/modules/rendering.js
- #1940 bug fix
- #1940 bug fix
> merge master into feature-cloud-enhancement
